const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const path = require('path');
const base = 'http://127.0.0.1:8871';
const output = path.join(__dirname, 'verification');
fs.mkdirSync(output, {recursive:true});

(async()=>{
  const enterManage=async page=>{
    await page.locator('.brand-name').click();
    await page.locator('#page-hall').waitFor({state:'visible'});
    await page.locator('.hall-door.door-creator').getByRole('button',{name:'进入创作者端'}).click();
    await page.locator('#page-workbench').waitFor({state:'visible'});
    await page.locator('#creator-nav').getByRole('button',{name:'我的商品'}).click();
    await page.locator('#page-manage').waitFor({state:'visible'});
  };
  const browser = await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
  const results=[];
  const errors=[];
  const managerPage=await browser.newPage({viewport:{width:1440,height:1000}});
  managerPage.on('pageerror',e=>errors.push(e.message));
  await managerPage.goto(base,{waitUntil:'networkidle'});
  await managerPage.locator('#account-area').getByRole('button').click();
  const account=fs.readFileSync(path.join(__dirname,'.local/browser-qa/本机管理者账号.txt'),'utf8');
  const password=account.split('密码：')[1].trim();
  await managerPage.locator('#auth-username').fill('manager');
  await managerPage.locator('#auth-password').fill(password);
  await managerPage.locator('#auth-submit').click();
  await managerPage.locator('#auth-dialog').waitFor({state:'hidden'});
  await enterManage(managerPage);
  await managerPage.locator('#manager-name').fill('QA管理商品・测试资料');
  await managerPage.locator('#manager-brand').fill('测试管理者');
  await managerPage.locator('#manager-form').selectOption('perfume');
  await managerPage.locator('#manager-description').fill('测试商品的木质描述；非真实在售产品。');
  await managerPage.locator('#manager-upload-form details summary').click();
  await managerPage.locator('#manager-notes').fill('木质、树脂、甜香');
  await managerPage.locator('#manager-ingredients').fill('PRIVATE_INGREDIENT_SECRET');
  await managerPage.locator('#manager-personal-notes').fill('PRIVATE_PERSONAL_SECRET');
  await managerPage.locator('#manager-files').setInputFiles('/tmp/xihack-browser-label.jpg');
  await managerPage.locator('#manager-upload-form').getByRole('button',{name:'保存并分析'}).click();
  await managerPage.locator('#detail-dialog').waitFor({state:'visible'});
  const analysisText=await managerPage.locator('#detail-content').innerText();
  if(!analysisText.includes('成分')||!analysisText.includes('木质'))throw new Error('资料拆解没有分层显示');
  await managerPage.locator('#detail-dialog .close-dialog').click();
  const record=managerPage.locator('#manager-records [data-record]').first();
  const productId=await record.getAttribute('data-record');
  await record.locator('input[name=purchase_url]').fill('https://example.com/qa-product');
  await record.locator('input[name=public_fields][value=image]').check();
  await record.locator('input[name=public_fields][value=ingredients]').uncheck();
  await record.getByRole('button',{name:'挂到首页',exact:true}).click();
  await managerPage.locator('#manager-records').getByText('已挂首页',{exact:true}).first().waitFor();
  await managerPage.getByRole('button',{name:'回到香事',exact:true}).click();
  await managerPage.locator('#home-products').getByText('QA管理商品・测试资料',{exact:true}).waitFor();
  const home=await managerPage.locator('#home-products').innerText();
  if(home.includes('PRIVATE_'))throw new Error('首页泄露私人资料');
  results.push('管理者真实登录、照片上传拆解、选择公开字段、首页推荐与导购入口');

  const userContext=await browser.newContext({viewport:{width:1440,height:1000}});
  const userPage=await userContext.newPage();
  userPage.on('pageerror',e=>errors.push(e.message));
  await userPage.goto(base,{waitUntil:'networkidle'});
  await userPage.locator('#account-area').getByRole('button').click();
  await userPage.getByRole('button',{name:'注册香友',exact:true}).click();
  await userPage.locator('#auth-username').fill('browser_user_'+Date.now());
  await userPage.locator('#auth-password').fill('Browser-Testing-123');
  await userPage.locator('#auth-submit').click();
  await userPage.locator('#auth-dialog').waitFor({state:'hidden'});
  if(await userPage.locator('#creator-nav').isVisible())throw new Error('普通用户看到创作者导航');
  const denied=await userPage.evaluate(async(id)=>{
    const session=await (await fetch('/api/session')).json();
    return (await fetch(`/api/products/${id}/publish`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf_token},body:'{}'})).status;
  },productId);
  if(denied!==403)throw new Error('普通用户可绕过首页权限');
  await userPage.getByRole('button',{name:'我家的香',exact:true}).click();
  await userPage.locator('#private-name').fill('QA我家的香・私人');
  await userPage.locator('#private-description').fill('标签说明香调：木质、草本。');
  await userPage.locator('#private-upload-form').getByRole('button',{name:'保存并分析'}).click();
  await userPage.locator('#detail-dialog').waitFor({state:'visible'});
  await userPage.locator('#detail-dialog .close-dialog').click();
  await userPage.locator('#private-records').getByText('QA我家的香・私人',{exact:true}).waitFor();
  await userPage.getByRole('button',{name:'推荐香品',exact:true}).click();
  if((await userPage.locator('#home-products').innerText()).includes('QA我家的香'))throw new Error('用户私有上传出现在首页');
  results.push('普通注册、本人私人咨询、首页不可发布及隐私隔离');

  await userPage.getByRole('button',{name:'调香案',exact:true}).click();
  await userPage.locator('.preset-drawer summary').click();
  await userPage.locator('[data-action=use-preset][data-index="1"]').click();
  if(await userPage.locator('#design-words').inputValue())throw new Error('预设意图被伪装成用户原话');
  const sweetPref=userPage.locator('[data-action=toggle-facet][data-group=preferred][data-key=sweet]');
  if(await sweetPref.getAttribute('aria-pressed')==='true')await sweetPref.click();
  const sweetLess=userPage.locator('[data-action=toggle-facet][data-group=deemphasized][data-key=sweet]');
  if(await sweetLess.getAttribute('aria-pressed')!=='true')await sweetLess.click();
  await userPage.locator('#design-scene').fill('测试阅读时光');
  await userPage.locator('#generate-design').click();
  await userPage.locator('#candidate-results .candidate-card').first().waitFor();
  if(await userPage.locator('#candidate-results .candidate-card').count()!==2)throw new Error('没有两份可比较候选');
  await userPage.screenshot({path:path.join(output,'调香工作台.png'),fullPage:true});
  await userPage.locator('#candidate-results .candidate-card').first().getByRole('button',{name:'命名留笺'}).click();
  await userPage.locator('#card-dialog').waitFor({state:'visible'});
  await userPage.locator('#card-name').fill('案上木韵');
  const downloadPromise=userPage.waitForEvent('download');
  await userPage.locator('#download-card').click();
  const downloaded=await downloadPromise;
  await downloaded.saveAs(path.join(output,'香笺.png'));
  if(fs.statSync(path.join(output,'香笺.png')).size<1000)throw new Error('导出图片无效');
  results.push('草案进入、中文偏好、自由调整、双候选与实际PNG导出');
  await userPage.locator('#card-to-integration').click();
  await userPage.locator('#integration-scene').selectOption('reading');
  await userPage.locator('#handoff-design').click();
  await userPage.locator('[data-action=confirm-simulation]').waitFor();
  await userPage.locator('[data-action=confirm-simulation]').click();
  await userPage.locator('#simulation-on').click();
  await userPage.locator('#simulation-duration').fill('12');
  await userPage.locator('#simulation-timer').click();
  await userPage.locator('#simulation-off').click();
  results.push('香笺交接、模拟确认、开启定时关闭');

  await userPage.setViewportSize({width:390,height:844});
  await userPage.getByRole('button',{name:'调香案',exact:true}).click();
  await userPage.screenshot({path:path.join(output,'手机调香.png'),fullPage:true});
  const overflow=await userPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
  if(overflow)throw new Error('手机界面横向溢出');
  results.push('390px手机布局无横向溢出');
  await enterManage(managerPage);
  await managerPage.locator(`[data-record="${productId}"]`).getByRole('button',{name:'从首页撤下'}).click();
  await managerPage.getByRole('button',{name:'回到香事',exact:true}).click();
  if((await managerPage.locator('#home-products').innerText()).includes('QA管理商品'))throw new Error('撤下后仍在首页');
  results.push('管理者撤下商品后首页不再展示');
  if(errors.length)throw new Error('浏览器错误:'+errors.join(';'));
  fs.writeFileSync(path.join(output,'浏览器验收.json'),JSON.stringify({passed:true,results,errors,scope:'真实本地Chrome与隔离测试资料；无真实商家成交、无真实香气验证'},null,2));
  console.log(JSON.stringify({passed:true,results,errors}));
  await browser.close();
})().catch(e=>{console.error(e.stack);process.exit(1)});
